package oil.oil_test.POJO;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class CheckMain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkmain_table.checkMainID
     *
     * @mbg.generated
     */
    private Long checkMainID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkmain_table.wareID
     *
     * @mbg.generated
     */
    private Long wareID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkmain_table.userID
     *
     * @mbg.generated
     */
    private Long userID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkmain_table.checkDate
     *
     * @mbg.generated
     */
    private Date checkDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkmain_table.checkUser
     *
     * @mbg.generated
     */
    private String checkUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkmain_table.checkManager
     *
     * @mbg.generated
     */
    private String checkManager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkmain_table.checkTime
     *
     * @mbg.generated
     */
    private Date checkTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkmain_table.checkResult
     *
     * @mbg.generated
     */
    private String checkResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkmain_table.checkState
     *
     * @mbg.generated
     */
    private Integer checkState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkmain_table.checkMainID
     *
     * @return the value of checkmain_table.checkMainID
     *
     * @mbg.generated
     */
    public Long getCheckMainID() {
        return checkMainID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkmain_table.checkMainID
     *
     * @param checkMainID the value for checkmain_table.checkMainID
     *
     * @mbg.generated
     */
    public void setCheckMainID(Long checkMainID) {
        this.checkMainID = checkMainID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkmain_table.wareID
     *
     * @return the value of checkmain_table.wareID
     *
     * @mbg.generated
     */
    public Long getWareID() {
        return wareID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkmain_table.wareID
     *
     * @param wareID the value for checkmain_table.wareID
     *
     * @mbg.generated
     */
    public void setWareID(Long wareID) {
        this.wareID = wareID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkmain_table.userID
     *
     * @return the value of checkmain_table.userID
     *
     * @mbg.generated
     */
    public Long getUserID() {
        return userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkmain_table.userID
     *
     * @param userID the value for checkmain_table.userID
     *
     * @mbg.generated
     */
    public void setUserID(Long userID) {
        this.userID = userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkmain_table.checkDate
     *
     * @return the value of checkmain_table.checkDate
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd",timezone = "GMT+8")
    public Date getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkmain_table.checkDate
     *
     * @param checkDate the value for checkmain_table.checkDate
     *
     * @mbg.generated
     */
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkmain_table.checkUser
     *
     * @return the value of checkmain_table.checkUser
     *
     * @mbg.generated
     */
    public String getCheckUser() {
        return checkUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkmain_table.checkUser
     *
     * @param checkUser the value for checkmain_table.checkUser
     *
     * @mbg.generated
     */
    public void setCheckUser(String checkUser) {
        this.checkUser = checkUser == null ? null : checkUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkmain_table.checkManager
     *
     * @return the value of checkmain_table.checkManager
     *
     * @mbg.generated
     */
    public String getCheckManager() {
        return checkManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkmain_table.checkManager
     *
     * @param checkManager the value for checkmain_table.checkManager
     *
     * @mbg.generated
     */
    public void setCheckManager(String checkManager) {
        this.checkManager = checkManager == null ? null : checkManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkmain_table.checkTime
     *
     * @return the value of checkmain_table.checkTime
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd",timezone = "GMT+8")
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkmain_table.checkTime
     *
     * @param checkTime the value for checkmain_table.checkTime
     *
     * @mbg.generated
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkmain_table.checkResult
     *
     * @return the value of checkmain_table.checkResult
     *
     * @mbg.generated
     */
    public String getCheckResult() {
        return checkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkmain_table.checkResult
     *
     * @param checkResult the value for checkmain_table.checkResult
     *
     * @mbg.generated
     */
    public void setCheckResult(String checkResult) {
        this.checkResult = checkResult == null ? null : checkResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkmain_table.checkState
     *
     * @return the value of checkmain_table.checkState
     *
     * @mbg.generated
     */
    public Integer getCheckState() {
        return checkState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkmain_table.checkState
     *
     * @param checkState the value for checkmain_table.checkState
     *
     * @mbg.generated
     */
    public void setCheckState(Integer checkState) {
        this.checkState = checkState;
    }
}