package oil.oil_test.POJO;

public class CheckDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkdetail_table.checkID
     *
     * @mbg.generated
     */
    private Long checkID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkdetail_table.stockID
     *
     * @mbg.generated
     */
    private Long stockID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkdetail_table.checkMainID
     *
     * @mbg.generated
     */
    private Long checkMainID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkdetail_table.checkNum
     *
     * @mbg.generated
     */
    private Float checkNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkdetail_table.checkChangeNum
     *
     * @mbg.generated
     */
    private Float checkChangeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkdetail_table.stockRealNum
     *
     * @mbg.generated
     */
    private Float stockRealNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkdetail_table.checkID
     *
     * @return the value of checkdetail_table.checkID
     *
     * @mbg.generated
     */
    public Long getCheckID() {
        return checkID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkdetail_table.checkID
     *
     * @param checkID the value for checkdetail_table.checkID
     *
     * @mbg.generated
     */
    public void setCheckID(Long checkID) {
        this.checkID = checkID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkdetail_table.stockID
     *
     * @return the value of checkdetail_table.stockID
     *
     * @mbg.generated
     */
    public Long getStockID() {
        return stockID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkdetail_table.stockID
     *
     * @param stockID the value for checkdetail_table.stockID
     *
     * @mbg.generated
     */
    public void setStockID(Long stockID) {
        this.stockID = stockID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkdetail_table.checkMainID
     *
     * @return the value of checkdetail_table.checkMainID
     *
     * @mbg.generated
     */
    public Long getCheckMainID() {
        return checkMainID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkdetail_table.checkMainID
     *
     * @param checkMainID the value for checkdetail_table.checkMainID
     *
     * @mbg.generated
     */
    public void setCheckMainID(Long checkMainID) {
        this.checkMainID = checkMainID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkdetail_table.checkNum
     *
     * @return the value of checkdetail_table.checkNum
     *
     * @mbg.generated
     */
    public Float getCheckNum() {
        return checkNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkdetail_table.checkNum
     *
     * @param checkNum the value for checkdetail_table.checkNum
     *
     * @mbg.generated
     */
    public void setCheckNum(Float checkNum) {
        this.checkNum = checkNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkdetail_table.checkChangeNum
     *
     * @return the value of checkdetail_table.checkChangeNum
     *
     * @mbg.generated
     */
    public Float getCheckChangeNum() {
        return checkChangeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkdetail_table.checkChangeNum
     *
     * @param checkChangeNum the value for checkdetail_table.checkChangeNum
     *
     * @mbg.generated
     */
    public void setCheckChangeNum(Float checkChangeNum) {
        this.checkChangeNum = checkChangeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkdetail_table.stockRealNum
     *
     * @return the value of checkdetail_table.stockRealNum
     *
     * @mbg.generated
     */
    public Float getStockRealNum() {
        return stockRealNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkdetail_table.stockRealNum
     *
     * @param stockRealNum the value for checkdetail_table.stockRealNum
     *
     * @mbg.generated
     */
    public void setStockRealNum(Float stockRealNum) {
        this.stockRealNum = stockRealNum;
    }
}