package oil.oil_test.POJO;

public class Dis {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_table.disID
     *
     * @mbg.generated
     */
    private Long disID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_table.manageID
     *
     * @mbg.generated
     */
    private Long manageID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_table.oilID
     *
     * @mbg.generated
     */
    private Long oilID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_table.wareID
     *
     * @mbg.generated
     */
    private Long wareID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_table.userID
     *
     * @mbg.generated
     */
    private Long userID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_table.disNumber
     *
     * @mbg.generated
     */
    private Float disNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_table.disNote
     *
     * @mbg.generated
     */
    private String disNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_table.disState
     *
     * @mbg.generated
     */
    private Integer disState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_table.appID
     *
     * @mbg.generated
     */
    private Long appID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_table.disID
     *
     * @return the value of dis_table.disID
     *
     * @mbg.generated
     */
    public Long getDisID() {
        return disID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_table.disID
     *
     * @param disID the value for dis_table.disID
     *
     * @mbg.generated
     */
    public void setDisID(Long disID) {
        this.disID = disID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_table.manageID
     *
     * @return the value of dis_table.manageID
     *
     * @mbg.generated
     */
    public Long getManageID() {
        return manageID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_table.manageID
     *
     * @param manageID the value for dis_table.manageID
     *
     * @mbg.generated
     */
    public void setManageID(Long manageID) {
        this.manageID = manageID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_table.oilID
     *
     * @return the value of dis_table.oilID
     *
     * @mbg.generated
     */
    public Long getOilID() {
        return oilID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_table.oilID
     *
     * @param oilID the value for dis_table.oilID
     *
     * @mbg.generated
     */
    public void setOilID(Long oilID) {
        this.oilID = oilID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_table.wareID
     *
     * @return the value of dis_table.wareID
     *
     * @mbg.generated
     */
    public Long getWareID() {
        return wareID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_table.wareID
     *
     * @param wareID the value for dis_table.wareID
     *
     * @mbg.generated
     */
    public void setWareID(Long wareID) {
        this.wareID = wareID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_table.userID
     *
     * @return the value of dis_table.userID
     *
     * @mbg.generated
     */
    public Long getUserID() {
        return userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_table.userID
     *
     * @param userID the value for dis_table.userID
     *
     * @mbg.generated
     */
    public void setUserID(Long userID) {
        this.userID = userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_table.disNumber
     *
     * @return the value of dis_table.disNumber
     *
     * @mbg.generated
     */
    public Float getDisNumber() {
        return disNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_table.disNumber
     *
     * @param disNumber the value for dis_table.disNumber
     *
     * @mbg.generated
     */
    public void setDisNumber(Float disNumber) {
        this.disNumber = disNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_table.disNote
     *
     * @return the value of dis_table.disNote
     *
     * @mbg.generated
     */
    public String getDisNote() {
        return disNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_table.disNote
     *
     * @param disNote the value for dis_table.disNote
     *
     * @mbg.generated
     */
    public void setDisNote(String disNote) {
        this.disNote = disNote == null ? null : disNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_table.disState
     *
     * @return the value of dis_table.disState
     *
     * @mbg.generated
     */
    public Integer getDisState() {
        return disState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_table.disState
     *
     * @param disState the value for dis_table.disState
     *
     * @mbg.generated
     */
    public void setDisState(Integer disState) {
        this.disState = disState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_table.appID
     *
     * @return the value of dis_table.appID
     *
     * @mbg.generated
     */
    public Long getAppID() {
        return appID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_table.appID
     *
     * @param appID the value for dis_table.appID
     *
     * @mbg.generated
     */
    public void setAppID(Long appID) {
        this.appID = appID;
    }
}