package oil.oil_test.POJO;

public class Group {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_table.groupID
     *
     * @mbg.generated
     */
    private Long groupID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_table.groupUpName
     *
     * @mbg.generated
     */
    private String groupUpName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_table.groupCode
     *
     * @mbg.generated
     */
    private String groupCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_table.groupName
     *
     * @mbg.generated
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_table.groupNature
     *
     * @mbg.generated
     */
    private Integer groupNature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_table.groupZQ
     *
     * @mbg.generated
     */
    private String groupZQ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_table.groupJT
     *
     * @mbg.generated
     */
    private String groupJT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_table.groupID
     *
     * @return the value of group_table.groupID
     *
     * @mbg.generated
     */
    public Long getGroupID() {
        return groupID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_table.groupID
     *
     * @param groupID the value for group_table.groupID
     *
     * @mbg.generated
     */
    public void setGroupID(Long groupID) {
        this.groupID = groupID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_table.groupUpName
     *
     * @return the value of group_table.groupUpName
     *
     * @mbg.generated
     */
    public String getGroupUpName() {
        return groupUpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_table.groupUpName
     *
     * @param groupUpName the value for group_table.groupUpName
     *
     * @mbg.generated
     */
    public void setGroupUpName(String groupUpName) {
        this.groupUpName = groupUpName == null ? null : groupUpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_table.groupCode
     *
     * @return the value of group_table.groupCode
     *
     * @mbg.generated
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_table.groupCode
     *
     * @param groupCode the value for group_table.groupCode
     *
     * @mbg.generated
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode == null ? null : groupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_table.groupName
     *
     * @return the value of group_table.groupName
     *
     * @mbg.generated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_table.groupName
     *
     * @param groupName the value for group_table.groupName
     *
     * @mbg.generated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_table.groupNature
     *
     * @return the value of group_table.groupNature
     *
     * @mbg.generated
     */
    public Integer getGroupNature() {
        return groupNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_table.groupNature
     *
     * @param groupNature the value for group_table.groupNature
     *
     * @mbg.generated
     */
    public void setGroupNature(Integer groupNature) {
        this.groupNature = groupNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_table.groupZQ
     *
     * @return the value of group_table.groupZQ
     *
     * @mbg.generated
     */
    public String getGroupZQ() {
        return groupZQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_table.groupZQ
     *
     * @param groupZQ the value for group_table.groupZQ
     *
     * @mbg.generated
     */
    public void setGroupZQ(String groupZQ) {
        this.groupZQ = groupZQ == null ? null : groupZQ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_table.groupJT
     *
     * @return the value of group_table.groupJT
     *
     * @mbg.generated
     */
    public String getGroupJT() {
        return groupJT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_table.groupJT
     *
     * @param groupJT the value for group_table.groupJT
     *
     * @mbg.generated
     */
    public void setGroupJT(String groupJT) {
        this.groupJT = groupJT == null ? null : groupJT.trim();
    }
}