package oil.oil_test.POJO;

public class House {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_table.wareID
     *
     * @mbg.generated
     */
    private Long wareID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_table.groupID
     *
     * @mbg.generated
     */
    private Long groupID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_table.wareTotal
     *
     * @mbg.generated
     */
    private Float wareTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_table.ltName
     *
     * @mbg.generated
     */
    private String ltName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_table.jtName
     *
     * @mbg.generated
     */
    private String jtName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_table.zqName
     *
     * @mbg.generated
     */
    private String zqName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_table.wareCode
     *
     * @mbg.generated
     */
    private String wareCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_table.wareName
     *
     * @mbg.generated
     */
    private String wareName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_table.wareShen
     *
     * @mbg.generated
     */
    private String wareShen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_table.wareShi
     *
     * @mbg.generated
     */
    private String wareShi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_table.wareXian
     *
     * @mbg.generated
     */
    private String wareXian;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_table.wareID
     *
     * @return the value of house_table.wareID
     *
     * @mbg.generated
     */
    public Long getWareID() {
        return wareID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_table.wareID
     *
     * @param wareID the value for house_table.wareID
     *
     * @mbg.generated
     */
    public void setWareID(Long wareID) {
        this.wareID = wareID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_table.groupID
     *
     * @return the value of house_table.groupID
     *
     * @mbg.generated
     */
    public Long getGroupID() {
        return groupID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_table.groupID
     *
     * @param groupID the value for house_table.groupID
     *
     * @mbg.generated
     */
    public void setGroupID(Long groupID) {
        this.groupID = groupID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_table.wareTotal
     *
     * @return the value of house_table.wareTotal
     *
     * @mbg.generated
     */
    public Float getWareTotal() {
        return wareTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_table.wareTotal
     *
     * @param wareTotal the value for house_table.wareTotal
     *
     * @mbg.generated
     */
    public void setWareTotal(Float wareTotal) {
        this.wareTotal = wareTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_table.ltName
     *
     * @return the value of house_table.ltName
     *
     * @mbg.generated
     */
    public String getLtName() {
        return ltName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_table.ltName
     *
     * @param ltName the value for house_table.ltName
     *
     * @mbg.generated
     */
    public void setLtName(String ltName) {
        this.ltName = ltName == null ? null : ltName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_table.jtName
     *
     * @return the value of house_table.jtName
     *
     * @mbg.generated
     */
    public String getJtName() {
        return jtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_table.jtName
     *
     * @param jtName the value for house_table.jtName
     *
     * @mbg.generated
     */
    public void setJtName(String jtName) {
        this.jtName = jtName == null ? null : jtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_table.zqName
     *
     * @return the value of house_table.zqName
     *
     * @mbg.generated
     */
    public String getZqName() {
        return zqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_table.zqName
     *
     * @param zqName the value for house_table.zqName
     *
     * @mbg.generated
     */
    public void setZqName(String zqName) {
        this.zqName = zqName == null ? null : zqName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_table.wareCode
     *
     * @return the value of house_table.wareCode
     *
     * @mbg.generated
     */
    public String getWareCode() {
        return wareCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_table.wareCode
     *
     * @param wareCode the value for house_table.wareCode
     *
     * @mbg.generated
     */
    public void setWareCode(String wareCode) {
        this.wareCode = wareCode == null ? null : wareCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_table.wareName
     *
     * @return the value of house_table.wareName
     *
     * @mbg.generated
     */
    public String getWareName() {
        return wareName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_table.wareName
     *
     * @param wareName the value for house_table.wareName
     *
     * @mbg.generated
     */
    public void setWareName(String wareName) {
        this.wareName = wareName == null ? null : wareName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_table.wareShen
     *
     * @return the value of house_table.wareShen
     *
     * @mbg.generated
     */
    public String getWareShen() {
        return wareShen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_table.wareShen
     *
     * @param wareShen the value for house_table.wareShen
     *
     * @mbg.generated
     */
    public void setWareShen(String wareShen) {
        this.wareShen = wareShen == null ? null : wareShen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_table.wareShi
     *
     * @return the value of house_table.wareShi
     *
     * @mbg.generated
     */
    public String getWareShi() {
        return wareShi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_table.wareShi
     *
     * @param wareShi the value for house_table.wareShi
     *
     * @mbg.generated
     */
    public void setWareShi(String wareShi) {
        this.wareShi = wareShi == null ? null : wareShi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_table.wareXian
     *
     * @return the value of house_table.wareXian
     *
     * @mbg.generated
     */
    public String getWareXian() {
        return wareXian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_table.wareXian
     *
     * @param wareXian the value for house_table.wareXian
     *
     * @mbg.generated
     */
    public void setWareXian(String wareXian) {
        this.wareXian = wareXian == null ? null : wareXian.trim();
    }
}