package oil.oil_test.POJO;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Manage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_table.manageID
     *
     * @mbg.generated
     */
    private Long manageID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_table.appID
     *
     * @mbg.generated
     */
    private Long appID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_table.userID
     *
     * @mbg.generated
     */
    private Long userID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_table.manageState
     *
     * @mbg.generated
     */
    private Integer manageState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_table.manageDate
     *
     * @mbg.generated
     */
    private Date manageDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_table.manageNote
     *
     * @mbg.generated
     */
    private String manageNote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_table.manageID
     *
     * @return the value of manage_table.manageID
     *
     * @mbg.generated
     */
    public Long getManageID() {
        return manageID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_table.manageID
     *
     * @param manageID the value for manage_table.manageID
     *
     * @mbg.generated
     */
    public void setManageID(Long manageID) {
        this.manageID = manageID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_table.appID
     *
     * @return the value of manage_table.appID
     *
     * @mbg.generated
     */
    public Long getAppID() {
        return appID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_table.appID
     *
     * @param appID the value for manage_table.appID
     *
     * @mbg.generated
     */
    public void setAppID(Long appID) {
        this.appID = appID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_table.userID
     *
     * @return the value of manage_table.userID
     *
     * @mbg.generated
     */
    public Long getUserID() {
        return userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_table.userID
     *
     * @param userID the value for manage_table.userID
     *
     * @mbg.generated
     */
    public void setUserID(Long userID) {
        this.userID = userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_table.manageState
     *
     * @return the value of manage_table.manageState
     *
     * @mbg.generated
     */
    public Integer getManageState() {
        return manageState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_table.manageState
     *
     * @param manageState the value for manage_table.manageState
     *
     * @mbg.generated
     */
    public void setManageState(Integer manageState) {
        this.manageState = manageState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_table.manageDate
     *
     * @return the value of manage_table.manageDate
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd",timezone = "GMT+8")
    public Date getManageDate() {
        return manageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_table.manageDate
     *
     * @param manageDate the value for manage_table.manageDate
     *
     * @mbg.generated
     */
    public void setManageDate(Date manageDate) {
        this.manageDate = manageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_table.manageNote
     *
     * @return the value of manage_table.manageNote
     *
     * @mbg.generated
     */
    public String getManageNote() {
        return manageNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_table.manageNote
     *
     * @param manageNote the value for manage_table.manageNote
     *
     * @mbg.generated
     */
    public void setManageNote(String manageNote) {
        this.manageNote = manageNote == null ? null : manageNote.trim();
    }
}