package oil.oil_test.POJO;

public class Oil {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_table.oilID
     *
     * @mbg.generated
     */
    private Long oilID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_table.oilName
     *
     * @mbg.generated
     */
    private String oilName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_table.oilTypeID
     *
     * @mbg.generated
     */
    private Integer oilTypeID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_table.oilCode
     *
     * @mbg.generated
     */
    private String oilCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_table.oilGruantee
     *
     * @mbg.generated
     */
    private Integer oilGruantee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_table.oilID
     *
     * @return the value of oil_table.oilID
     *
     * @mbg.generated
     */
    public Long getOilID() {
        return oilID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_table.oilID
     *
     * @param oilID the value for oil_table.oilID
     *
     * @mbg.generated
     */
    public void setOilID(Long oilID) {
        this.oilID = oilID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_table.oilName
     *
     * @return the value of oil_table.oilName
     *
     * @mbg.generated
     */
    public String getOilName() {
        return oilName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_table.oilName
     *
     * @param oilName the value for oil_table.oilName
     *
     * @mbg.generated
     */
    public void setOilName(String oilName) {
        this.oilName = oilName == null ? null : oilName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_table.oilTypeID
     *
     * @return the value of oil_table.oilTypeID
     *
     * @mbg.generated
     */
    public Integer getOilTypeID() {
        return oilTypeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_table.oilTypeID
     *
     * @param oilTypeID the value for oil_table.oilTypeID
     *
     * @mbg.generated
     */
    public void setOilTypeID(Integer oilTypeID) {
        this.oilTypeID = oilTypeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_table.oilCode
     *
     * @return the value of oil_table.oilCode
     *
     * @mbg.generated
     */
    public String getOilCode() {
        return oilCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_table.oilCode
     *
     * @param oilCode the value for oil_table.oilCode
     *
     * @mbg.generated
     */
    public void setOilCode(String oilCode) {
        this.oilCode = oilCode == null ? null : oilCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_table.oilGruantee
     *
     * @return the value of oil_table.oilGruantee
     *
     * @mbg.generated
     */
    public Integer getOilGruantee() {
        return oilGruantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_table.oilGruantee
     *
     * @param oilGruantee the value for oil_table.oilGruantee
     *
     * @mbg.generated
     */
    public void setOilGruantee(Integer oilGruantee) {
        this.oilGruantee = oilGruantee;
    }
}