package oil.oil_test.POJO;

public class OilType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oiltype_table.oilTypeID
     *
     * @mbg.generated
     */
    private Integer oilTypeID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oiltype_table.oilType
     *
     * @mbg.generated
     */
    private String oilType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oiltype_table.oilTypeID
     *
     * @return the value of oiltype_table.oilTypeID
     *
     * @mbg.generated
     */
    public Integer getOilTypeID() {
        return oilTypeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oiltype_table.oilTypeID
     *
     * @param oilTypeID the value for oiltype_table.oilTypeID
     *
     * @mbg.generated
     */
    public void setOilTypeID(Integer oilTypeID) {
        this.oilTypeID = oilTypeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oiltype_table.oilType
     *
     * @return the value of oiltype_table.oilType
     *
     * @mbg.generated
     */
    public String getOilType() {
        return oilType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oiltype_table.oilType
     *
     * @param oilType the value for oiltype_table.oilType
     *
     * @mbg.generated
     */
    public void setOilType(String oilType) {
        this.oilType = oilType == null ? null : oilType.trim();
    }
}