package oil.oil_test.POJO;

public class Power {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_table.powerID
     *
     * @mbg.generated
     */
    private Long powerID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_table.powerCode
     *
     * @mbg.generated
     */
    private Integer powerCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_table.powerNote
     *
     * @mbg.generated
     */
    private String powerNote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_table.powerID
     *
     * @return the value of power_table.powerID
     *
     * @mbg.generated
     */
    public Long getPowerID() {
        return powerID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_table.powerID
     *
     * @param powerID the value for power_table.powerID
     *
     * @mbg.generated
     */
    public void setPowerID(Long powerID) {
        this.powerID = powerID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_table.powerCode
     *
     * @return the value of power_table.powerCode
     *
     * @mbg.generated
     */
    public Integer getPowerCode() {
        return powerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_table.powerCode
     *
     * @param powerCode the value for power_table.powerCode
     *
     * @mbg.generated
     */
    public void setPowerCode(Integer powerCode) {
        this.powerCode = powerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_table.powerNote
     *
     * @return the value of power_table.powerNote
     *
     * @mbg.generated
     */
    public String getPowerNote() {
        return powerNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_table.powerNote
     *
     * @param powerNote the value for power_table.powerNote
     *
     * @mbg.generated
     */
    public void setPowerNote(String powerNote) {
        this.powerNote = powerNote == null ? null : powerNote.trim();
    }
}