package oil.oil_test.POJO;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Stock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_table.stockID
     *
     * @mbg.generated
     */
    private Long stockID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_table.wareID
     *
     * @mbg.generated
     */
    private Long wareID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_table.oilID
     *
     * @mbg.generated
     */
    private Long oilID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_table.stockNumber
     *
     * @mbg.generated
     */
    private Float stockNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_table.stockProduceDate
     *
     * @mbg.generated
     */
    private Date stockProduceDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_table.stockDate
     *
     * @mbg.generated
     */
    private Date stockDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_table.stockBarCode
     *
     * @mbg.generated
     */
    private String stockBarCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_table.stockReGruantee
     *
     * @mbg.generated
     */
    private Integer stockReGruantee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_table.stockState
     *
     * @mbg.generated
     */
    private String stockState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_table.stockNote
     *
     * @mbg.generated
     */
    private String stockNote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_table.stockID
     *
     * @return the value of stock_table.stockID
     *
     * @mbg.generated
     */
    public Long getStockID() {
        return stockID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_table.stockID
     *
     * @param stockID the value for stock_table.stockID
     *
     * @mbg.generated
     */
    public void setStockID(Long stockID) {
        this.stockID = stockID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_table.wareID
     *
     * @return the value of stock_table.wareID
     *
     * @mbg.generated
     */
    public Long getWareID() {
        return wareID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_table.wareID
     *
     * @param wareID the value for stock_table.wareID
     *
     * @mbg.generated
     */
    public void setWareID(Long wareID) {
        this.wareID = wareID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_table.oilID
     *
     * @return the value of stock_table.oilID
     *
     * @mbg.generated
     */
    public Long getOilID() {
        return oilID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_table.oilID
     *
     * @param oilID the value for stock_table.oilID
     *
     * @mbg.generated
     */
    public void setOilID(Long oilID) {
        this.oilID = oilID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_table.stockNumber
     *
     * @return the value of stock_table.stockNumber
     *
     * @mbg.generated
     */
    public Float getStockNumber() {
        return stockNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_table.stockNumber
     *
     * @param stockNumber the value for stock_table.stockNumber
     *
     * @mbg.generated
     */
    public void setStockNumber(Float stockNumber) {
        this.stockNumber = stockNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_table.stockProduceDate
     *
     * @return the value of stock_table.stockProduceDate
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd",timezone = "GMT+8")
    public Date getStockProduceDate() {
        return stockProduceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_table.stockProduceDate
     *
     * @param stockProduceDate the value for stock_table.stockProduceDate
     *
     * @mbg.generated
     */
    public void setStockProduceDate(Date stockProduceDate) {
        this.stockProduceDate = stockProduceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_table.stockDate
     *
     * @return the value of stock_table.stockDate
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd",timezone = "GMT+8")
    public Date getStockDate() {
        return stockDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_table.stockDate
     *
     * @param stockDate the value for stock_table.stockDate
     *
     * @mbg.generated
     */
    public void setStockDate(Date stockDate) {
        this.stockDate = stockDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_table.stockBarCode
     *
     * @return the value of stock_table.stockBarCode
     *
     * @mbg.generated
     */
    public String getStockBarCode() {
        return stockBarCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_table.stockBarCode
     *
     * @param stockBarCode the value for stock_table.stockBarCode
     *
     * @mbg.generated
     */
    public void setStockBarCode(String stockBarCode) {
        this.stockBarCode = stockBarCode == null ? null : stockBarCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_table.stockReGruantee
     *
     * @return the value of stock_table.stockReGruantee
     *
     * @mbg.generated
     */
    public Integer getStockReGruantee() {
        return stockReGruantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_table.stockReGruantee
     *
     * @param stockReGruantee the value for stock_table.stockReGruantee
     *
     * @mbg.generated
     */
    public void setStockReGruantee(Integer stockReGruantee) {
        this.stockReGruantee = stockReGruantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_table.stockState
     *
     * @return the value of stock_table.stockState
     *
     * @mbg.generated
     */
    public String getStockState() {
        return stockState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_table.stockState
     *
     * @param stockState the value for stock_table.stockState
     *
     * @mbg.generated
     */
    public void setStockState(String stockState) {
        this.stockState = stockState == null ? null : stockState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_table.stockNote
     *
     * @return the value of stock_table.stockNote
     *
     * @mbg.generated
     */
    public String getStockNote() {
        return stockNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_table.stockNote
     *
     * @param stockNote the value for stock_table.stockNote
     *
     * @mbg.generated
     */
    public void setStockNote(String stockNote) {
        this.stockNote = stockNote == null ? null : stockNote.trim();
    }

    @Override
    public String toString() {
        return "Stock{" +
                "stockID=" + stockID +
                ", wareID=" + wareID +
                ", oilID=" + oilID +
                ", stockNumber=" + stockNumber +
                ", stockProduceDate=" + stockProduceDate +
                ", stockDate=" + stockDate +
                ", stockBarCode='" + stockBarCode + '\'' +
                ", stockReGruantee=" + stockReGruantee +
                ", stockState='" + stockState + '\'' +
                ", stockNote='" + stockNote + '\'' +
                '}';
    }
}