package oil.oil_test.POJO;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class StockMain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockmain_table.stockMainID
     *
     * @mbg.generated
     */
    private Long stockMainID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockmain_table.oilID
     *
     * @mbg.generated
     */
    private Long oilID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockmain_table.wareID
     *
     * @mbg.generated
     */
    private Long wareID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockmain_table.stockMainNumber
     *
     * @mbg.generated
     */
    private Float stockMainNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockmain_table.stockMainProduceDate
     *
     * @mbg.generated
     */
    private Date stockMainProduceDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockmain_table.stockMainDate
     *
     * @mbg.generated
     */
    private Date stockMainDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockmain_table.stockMainBarCode
     *
     * @mbg.generated
     */
    private String stockMainBarCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockmain_table.stockMainReGruantee
     *
     * @mbg.generated
     */
    private Integer stockMainReGruantee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockmain_table.stockMainState
     *
     * @mbg.generated
     */
    private String stockMainState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockmain_table.stockMainNote
     *
     * @mbg.generated
     */
    private String stockMainNote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockmain_table.stockMainID
     *
     * @return the value of stockmain_table.stockMainID
     *
     * @mbg.generated
     */
    public Long getStockMainID() {
        return stockMainID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockmain_table.stockMainID
     *
     * @param stockMainID the value for stockmain_table.stockMainID
     *
     * @mbg.generated
     */
    public void setStockMainID(Long stockMainID) {
        this.stockMainID = stockMainID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockmain_table.oilID
     *
     * @return the value of stockmain_table.oilID
     *
     * @mbg.generated
     */
    public Long getOilID() {
        return oilID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockmain_table.oilID
     *
     * @param oilID the value for stockmain_table.oilID
     *
     * @mbg.generated
     */
    public void setOilID(Long oilID) {
        this.oilID = oilID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockmain_table.wareID
     *
     * @return the value of stockmain_table.wareID
     *
     * @mbg.generated
     */
    public Long getWareID() {
        return wareID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockmain_table.wareID
     *
     * @param wareID the value for stockmain_table.wareID
     *
     * @mbg.generated
     */
    public void setWareID(Long wareID) {
        this.wareID = wareID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockmain_table.stockMainNumber
     *
     * @return the value of stockmain_table.stockMainNumber
     *
     * @mbg.generated
     */
    public Float getStockMainNumber() {
        return stockMainNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockmain_table.stockMainNumber
     *
     * @param stockMainNumber the value for stockmain_table.stockMainNumber
     *
     * @mbg.generated
     */
    public void setStockMainNumber(Float stockMainNumber) {
        this.stockMainNumber = stockMainNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockmain_table.stockMainProduceDate
     *
     * @return the value of stockmain_table.stockMainProduceDate
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd",timezone = "GMT+8")
    public Date getStockMainProduceDate() {
        return stockMainProduceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockmain_table.stockMainProduceDate
     *
     * @param stockMainProduceDate the value for stockmain_table.stockMainProduceDate
     *
     * @mbg.generated
     */
    public void setStockMainProduceDate(Date stockMainProduceDate) {
        this.stockMainProduceDate = stockMainProduceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockmain_table.stockMainDate
     *
     * @return the value of stockmain_table.stockMainDate
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd",timezone = "GMT+8")
    public Date getStockMainDate() {
        return stockMainDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockmain_table.stockMainDate
     *
     * @param stockMainDate the value for stockmain_table.stockMainDate
     *
     * @mbg.generated
     */
    public void setStockMainDate(Date stockMainDate) {
        this.stockMainDate = stockMainDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockmain_table.stockMainBarCode
     *
     * @return the value of stockmain_table.stockMainBarCode
     *
     * @mbg.generated
     */
    public String getStockMainBarCode() {
        return stockMainBarCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockmain_table.stockMainBarCode
     *
     * @param stockMainBarCode the value for stockmain_table.stockMainBarCode
     *
     * @mbg.generated
     */
    public void setStockMainBarCode(String stockMainBarCode) {
        this.stockMainBarCode = stockMainBarCode == null ? null : stockMainBarCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockmain_table.stockMainReGruantee
     *
     * @return the value of stockmain_table.stockMainReGruantee
     *
     * @mbg.generated
     */
    public Integer getStockMainReGruantee() {
        return stockMainReGruantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockmain_table.stockMainReGruantee
     *
     * @param stockMainReGruantee the value for stockmain_table.stockMainReGruantee
     *
     * @mbg.generated
     */
    public void setStockMainReGruantee(Integer stockMainReGruantee) {
        this.stockMainReGruantee = stockMainReGruantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockmain_table.stockMainState
     *
     * @return the value of stockmain_table.stockMainState
     *
     * @mbg.generated
     */
    public String getStockMainState() {
        return stockMainState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockmain_table.stockMainState
     *
     * @param stockMainState the value for stockmain_table.stockMainState
     *
     * @mbg.generated
     */
    public void setStockMainState(String stockMainState) {
        this.stockMainState = stockMainState == null ? null : stockMainState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockmain_table.stockMainNote
     *
     * @return the value of stockmain_table.stockMainNote
     *
     * @mbg.generated
     */
    public String getStockMainNote() {
        return stockMainNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockmain_table.stockMainNote
     *
     * @param stockMainNote the value for stockmain_table.stockMainNote
     *
     * @mbg.generated
     */
    public void setStockMainNote(String stockMainNote) {
        this.stockMainNote = stockMainNote == null ? null : stockMainNote.trim();
    }

    @Override
    public String toString() {
        return "StockMain{" +
                "stockMainID=" + stockMainID +
                ", oilID=" + oilID +
                ", wareID=" + wareID +
                ", stockMainNumber=" + stockMainNumber +
                ", stockMainProduceDate=" + stockMainProduceDate +
                ", stockMainDate=" + stockMainDate +
                ", stockMainBarCode='" + stockMainBarCode + '\'' +
                ", stockMainReGruantee=" + stockMainReGruantee +
                ", stockMainState='" + stockMainState + '\'' +
                ", stockMainNote='" + stockMainNote + '\'' +
                '}';
    }
}