package oil.oil_test.POJO;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class StoreOut {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeout_table.storeOutID
     *
     * @mbg.generated
     */
    private Long storeOutID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeout_table.userID
     *
     * @mbg.generated
     */
    private Long userID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeout_table.wareID
     *
     * @mbg.generated
     */
    private Long wareID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeout_table.storeOutCode
     *
     * @mbg.generated
     */
    private String storeOutCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeout_table.storeOutType
     *
     * @mbg.generated
     */
    private Boolean storeOutType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeout_table.storeOutOil
     *
     * @mbg.generated
     */
    private String storeOutOil;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeout_table.storeOutPerson
     *
     * @mbg.generated
     */
    private String storeOutPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeout_table.storeOutDate
     *
     * @mbg.generated
     */

    private Date storeOutDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeout_table.storeOutState
     *
     * @mbg.generated
     */
    private Integer storeOutState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeout_table.storeOutNote
     *
     * @mbg.generated
     */
    private String storeOutNote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeout_table.storeOutID
     *
     * @return the value of storeout_table.storeOutID
     *
     * @mbg.generated
     */
    public Long getStoreOutID() {
        return storeOutID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeout_table.storeOutID
     *
     * @param storeOutID the value for storeout_table.storeOutID
     *
     * @mbg.generated
     */
    public void setStoreOutID(Long storeOutID) {
        this.storeOutID = storeOutID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeout_table.userID
     *
     * @return the value of storeout_table.userID
     *
     * @mbg.generated
     */
    public Long getUserID() {
        return userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeout_table.userID
     *
     * @param userID the value for storeout_table.userID
     *
     * @mbg.generated
     */
    public void setUserID(Long userID) {
        this.userID = userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeout_table.wareID
     *
     * @return the value of storeout_table.wareID
     *
     * @mbg.generated
     */
    public Long getWareID() {
        return wareID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeout_table.wareID
     *
     * @param wareID the value for storeout_table.wareID
     *
     * @mbg.generated
     */
    public void setWareID(Long wareID) {
        this.wareID = wareID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeout_table.storeOutCode
     *
     * @return the value of storeout_table.storeOutCode
     *
     * @mbg.generated
     */
    public String getStoreOutCode() {
        return storeOutCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeout_table.storeOutCode
     *
     * @param storeOutCode the value for storeout_table.storeOutCode
     *
     * @mbg.generated
     */
    public void setStoreOutCode(String storeOutCode) {
        this.storeOutCode = storeOutCode == null ? null : storeOutCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeout_table.storeOutType
     *
     * @return the value of storeout_table.storeOutType
     *
     * @mbg.generated
     */
    public Boolean getStoreOutType() {
        return storeOutType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeout_table.storeOutType
     *
     * @param storeOutType the value for storeout_table.storeOutType
     *
     * @mbg.generated
     */
    public void setStoreOutType(Boolean storeOutType) {
        this.storeOutType = storeOutType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeout_table.storeOutOil
     *
     * @return the value of storeout_table.storeOutOil
     *
     * @mbg.generated
     */
    public String getStoreOutOil() {
        return storeOutOil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeout_table.storeOutOil
     *
     * @param storeOutOil the value for storeout_table.storeOutOil
     *
     * @mbg.generated
     */
    public void setStoreOutOil(String storeOutOil) {
        this.storeOutOil = storeOutOil == null ? null : storeOutOil.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeout_table.storeOutPerson
     *
     * @return the value of storeout_table.storeOutPerson
     *
     * @mbg.generated
     */
    public String getStoreOutPerson() {
        return storeOutPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeout_table.storeOutPerson
     *
     * @param storeOutPerson the value for storeout_table.storeOutPerson
     *
     * @mbg.generated
     */
    public void setStoreOutPerson(String storeOutPerson) {
        this.storeOutPerson = storeOutPerson == null ? null : storeOutPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeout_table.storeOutDate
     *
     * @return the value of storeout_table.storeOutDate
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd",timezone = "GMT+8")
    public Date getStoreOutDate() {
        return storeOutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeout_table.storeOutDate
     *
     * @param storeOutDate the value for storeout_table.storeOutDate
     *
     * @mbg.generated
     */
    public void setStoreOutDate(Date storeOutDate) {
        this.storeOutDate = storeOutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeout_table.storeOutState
     *
     * @return the value of storeout_table.storeOutState
     *
     * @mbg.generated
     */
    public Integer getStoreOutState() {
        return storeOutState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeout_table.storeOutState
     *
     * @param storeOutState the value for storeout_table.storeOutState
     *
     * @mbg.generated
     */
    public void setStoreOutState(Integer storeOutState) {
        this.storeOutState = storeOutState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeout_table.storeOutNote
     *
     * @return the value of storeout_table.storeOutNote
     *
     * @mbg.generated
     */
    public String getStoreOutNote() {
        return storeOutNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeout_table.storeOutNote
     *
     * @param storeOutNote the value for storeout_table.storeOutNote
     *
     * @mbg.generated
     */
    public void setStoreOutNote(String storeOutNote) {
        this.storeOutNote = storeOutNote == null ? null : storeOutNote.trim();
    }
}