package oil.oil_test.POJO;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.stereotype.Repository;

import java.util.Date;

@Mapper
@Repository
public class StoreOutDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeoutdetail_table.storeDetailID
     *
     * @mbg.generated
     */
    private Long storeDetailID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeoutdetail_table.storeOutID
     *
     * @mbg.generated
     */
    private Long storeOutID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeoutdetail_table.oilID
     *
     * @mbg.generated
     */
    private Long oilID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeoutdetail_table.wareID
     *
     * @mbg.generated
     */
    private Long wareID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeoutdetail_table.storeDetailNum
     *
     * @mbg.generated
     */
    private Float storeDetailNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeoutdetail_table.storeDetailProDate
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date storeDetailProDate;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeoutdetail_table.storeDetailGra
     *
     * @mbg.generated
     */
    private Integer storeDetailGra;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeoutdetail_table.storeDetailID
     *
     * @return the value of storeoutdetail_table.storeDetailID
     *
     * @mbg.generated
     */
    public Long getStoreDetailID() {
        return storeDetailID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeoutdetail_table.storeDetailID
     *
     * @param storeDetailID the value for storeoutdetail_table.storeDetailID
     *
     * @mbg.generated
     */
    public void setStoreDetailID(Long storeDetailID) {
        this.storeDetailID = storeDetailID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeoutdetail_table.storeOutID
     *
     * @return the value of storeoutdetail_table.storeOutID
     *
     * @mbg.generated
     */
    public Long getStoreOutID() {
        return storeOutID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeoutdetail_table.storeOutID
     *
     * @param storeOutID the value for storeoutdetail_table.storeOutID
     *
     * @mbg.generated
     */
    public void setStoreOutID(Long storeOutID) {
        this.storeOutID = storeOutID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeoutdetail_table.oilID
     *
     * @return the value of storeoutdetail_table.oilID
     *
     * @mbg.generated
     */
    public Long getOilID() {
        return oilID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeoutdetail_table.oilID
     *
     * @param oilID the value for storeoutdetail_table.oilID
     *
     * @mbg.generated
     */
    public void setOilID(Long oilID) {
        this.oilID = oilID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeoutdetail_table.wareID
     *
     * @return the value of storeoutdetail_table.wareID
     *
     * @mbg.generated
     */
    public Long getWareID() {
        return wareID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeoutdetail_table.wareID
     *
     * @param wareID the value for storeoutdetail_table.wareID
     *
     * @mbg.generated
     */
    public void setWareID(Long wareID) {
        this.wareID = wareID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeoutdetail_table.storeDetailNum
     *
     * @return the value of storeoutdetail_table.storeDetailNum
     *
     * @mbg.generated
     */
    public Float getStoreDetailNum() {
        return storeDetailNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeoutdetail_table.storeDetailNum
     *
     * @param storeDetailNum the value for storeoutdetail_table.storeDetailNum
     *
     * @mbg.generated
     */
    public void setStoreDetailNum(Float storeDetailNum) {
        this.storeDetailNum = storeDetailNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeoutdetail_table.storeDetailProDate
     *
     * @return the value of storeoutdetail_table.storeDetailProDate
     *
     * @mbg.generated
     */

    @JsonFormat(pattern = "yyyy-MM-dd",timezone = "GMT+8")
    public Date getStoreDetailProDate() {
        return storeDetailProDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeoutdetail_table.storeDetailProDate
     *
     * @param storeDetailProDate the value for storeoutdetail_table.storeDetailProDate
     *
     * @mbg.generated
     */
    public void setStoreDetailProDate(Date storeDetailProDate) {
        this.storeDetailProDate = storeDetailProDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeoutdetail_table.storeDetailGra
     *
     * @return the value of storeoutdetail_table.storeDetailGra
     *
     * @mbg.generated
     */
    public Integer getStoreDetailGra() {
        return storeDetailGra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeoutdetail_table.storeDetailGra
     *
     * @param storeDetailGra the value for storeoutdetail_table.storeDetailGra
     *
     * @mbg.generated
     */
    public void setStoreDetailGra(Integer storeDetailGra) {
        this.storeDetailGra = storeDetailGra;
    }
}