package oil.oil_test.POJO;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.userID
     *
     * @mbg.generated
     */
    private Long userID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.groupID
     *
     * @mbg.generated
     */
    private Long groupID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.userAcount
     *
     * @mbg.generated
     */
    private String userAcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.userPassword
     *
     * @mbg.generated
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.userCode
     *
     * @mbg.generated
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.userName
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.userLT
     *
     * @mbg.generated
     */
    private String userLT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.userJT
     *
     * @mbg.generated
     */
    private String userJT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.userZQ
     *
     * @mbg.generated
     */
    private String userZQ;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.userID
     *
     * @return the value of user_table.userID
     *
     * @mbg.generated
     */
    public Long getUserID() {
        return userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.userID
     *
     * @param userID the value for user_table.userID
     *
     * @mbg.generated
     */
    public void setUserID(Long userID) {
        this.userID = userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.groupID
     *
     * @return the value of user_table.groupID
     *
     * @mbg.generated
     */
    public Long getGroupID() {
        return groupID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.groupID
     *
     * @param groupID the value for user_table.groupID
     *
     * @mbg.generated
     */
    public void setGroupID(Long groupID) {
        this.groupID = groupID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.userAcount
     *
     * @return the value of user_table.userAcount
     *
     * @mbg.generated
     */
    public String getUserAcount() {
        return userAcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.userAcount
     *
     * @param userAcount the value for user_table.userAcount
     *
     * @mbg.generated
     */
    public void setUserAcount(String userAcount) {
        this.userAcount = userAcount == null ? null : userAcount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.userPassword
     *
     * @return the value of user_table.userPassword
     *
     * @mbg.generated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.userPassword
     *
     * @param userPassword the value for user_table.userPassword
     *
     * @mbg.generated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.userCode
     *
     * @return the value of user_table.userCode
     *
     * @mbg.generated
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.userCode
     *
     * @param userCode the value for user_table.userCode
     *
     * @mbg.generated
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.userName
     *
     * @return the value of user_table.userName
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.userName
     *
     * @param userName the value for user_table.userName
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.userLT
     *
     * @return the value of user_table.userLT
     *
     * @mbg.generated
     */
    public String getUserLT() {
        return userLT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.userLT
     *
     * @param userLT the value for user_table.userLT
     *
     * @mbg.generated
     */
    public void setUserLT(String userLT) {
        this.userLT = userLT == null ? null : userLT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.userJT
     *
     * @return the value of user_table.userJT
     *
     * @mbg.generated
     */
    public String getUserJT() {
        return userJT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.userJT
     *
     * @param userJT the value for user_table.userJT
     *
     * @mbg.generated
     */
    public void setUserJT(String userJT) {
        this.userJT = userJT == null ? null : userJT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.userZQ
     *
     * @return the value of user_table.userZQ
     *
     * @mbg.generated
     */
    public String getUserZQ() {
        return userZQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.userZQ
     *
     * @param userZQ the value for user_table.userZQ
     *
     * @mbg.generated
     */
    public void setUserZQ(String userZQ) {
        this.userZQ = userZQ == null ? null : userZQ.trim();
    }

    @Override
    public String toString() {
        return "User{" +
                "userID=" + userID +
                ", groupID=" + groupID +
                ", userAcount='" + userAcount + '\'' +
                ", userPassword='" + userPassword + '\'' +
                ", userCode='" + userCode + '\'' +
                ", userName='" + userName + '\'' +
                ", userLT='" + userLT + '\'' +
                ", userJT='" + userJT + '\'' +
                ", userZQ='" + userZQ + '\'' +
                '}';
    }
}