package oil.oil_test.POJO;

public class UserPower {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpower_table.userPowerID
     *
     * @mbg.generated
     */
    private Long userPowerID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpower_table.userID
     *
     * @mbg.generated
     */
    private Long userID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpower_table.powerID
     *
     * @mbg.generated
     */
    private Long powerID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpower_table.userPowerID
     *
     * @return the value of userpower_table.userPowerID
     *
     * @mbg.generated
     */
    public Long getUserPowerID() {
        return userPowerID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpower_table.userPowerID
     *
     * @param userPowerID the value for userpower_table.userPowerID
     *
     * @mbg.generated
     */
    public void setUserPowerID(Long userPowerID) {
        this.userPowerID = userPowerID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpower_table.userID
     *
     * @return the value of userpower_table.userID
     *
     * @mbg.generated
     */
    public Long getUserID() {
        return userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpower_table.userID
     *
     * @param userID the value for userpower_table.userID
     *
     * @mbg.generated
     */
    public void setUserID(Long userID) {
        this.userID = userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpower_table.powerID
     *
     * @return the value of userpower_table.powerID
     *
     * @mbg.generated
     */
    public Long getPowerID() {
        return powerID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpower_table.powerID
     *
     * @param powerID the value for userpower_table.powerID
     *
     * @mbg.generated
     */
    public void setPowerID(Long powerID) {
        this.powerID = powerID;
    }
}