package oil.oil_test.dao;

import oil.oil_test.POJO.Apply;
import oil.oil_test.POJO.data.ApplyAll;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;


@Mapper
@Repository
public interface ApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long appID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_table
     *
     * @mbg.generated
     */
    int insert(Apply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_table
     *
     * @mbg.generated
     */
    int insertSelective(Apply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_table
     *
     * @mbg.generated
     */
    Apply selectByPrimaryKey(Long appID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Apply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Apply record);

    List<ApplyAll> selectByWareID(Long wareID);

    List<ApplyAll> selectByState();

    List<ApplyAll> selectByAppID(Long appID);

    List<ApplyAll> selectAll(Long wareID);
}