package oil.oil_test.dao;

import oil.oil_test.POJO.CheckMain;
import oil.oil_test.POJO.data.CheckMainAll;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface CheckMainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkmain_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long checkMainID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkmain_table
     *
     * @mbg.generated
     */
    int insert(CheckMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkmain_table
     *
     * @mbg.generated
     */
    int insertSelective(CheckMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkmain_table
     *
     * @mbg.generated
     */
    CheckMain selectByPrimaryKey(Long checkMainID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkmain_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CheckMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkmain_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CheckMain record);

    List<CheckMainAll> selectByWareID(@Param("wareID") Long wareID);
}