package oil.oil_test.dao;

import oil.oil_test.POJO.CheckDetail;
import oil.oil_test.POJO.data.CheckDetailAll;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;


@Mapper
@Repository
public interface CheckDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkdetail_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long checkID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkdetail_table
     *
     * @mbg.generated
     */
    int insert(CheckDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkdetail_table
     *
     * @mbg.generated
     */
    int insertSelective(CheckDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkdetail_table
     *
     * @mbg.generated
     */
    CheckDetail selectByPrimaryKey(Long checkID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkdetail_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CheckDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkdetail_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CheckDetail record);

    List<CheckDetail> seletctByCheckMainID(Long checkMainID);

    List<CheckDetailAll> checkDetailShow(Long checkMainID);
}