package oil.oil_test.dao;

import oil.oil_test.POJO.Common;

public interface CommonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long commonID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_table
     *
     * @mbg.generated
     */
    int insert(Common record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_table
     *
     * @mbg.generated
     */
    int insertSelective(Common record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_table
     *
     * @mbg.generated
     */
    Common selectByPrimaryKey(Long commonID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Common record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Common record);
}