package oil.oil_test.dao;

import oil.oil_test.POJO.House;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface HouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long wareID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_table
     *
     * @mbg.generated
     */
    int insert(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_table
     *
     * @mbg.generated
     */
    int insertSelective(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_table
     *
     * @mbg.generated
     */
    House selectByPrimaryKey(Long wareID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(House record);

    List<House> selectByGroupID(Long record);

    List<House> selectByGroupName(@Param("zqName") String zqName, @Param("jtName")String jtName, @Param("ltName") String ltName);



}