package oil.oil_test.dao;

import oil.oil_test.POJO.OilType;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface OilTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oiltype_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer oilTypeID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oiltype_table
     *
     * @mbg.generated
     */
    int insert(OilType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oiltype_table
     *
     * @mbg.generated
     */
    int insertSelective(OilType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oiltype_table
     *
     * @mbg.generated
     */
    OilType selectByPrimaryKey(Integer oilTypeID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oiltype_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OilType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oiltype_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OilType record);

    List<OilType> selectInfo();

    OilType selectByName(String record);
}