package oil.oil_test.dao;

import oil.oil_test.POJO.StoreOut;
import oil.oil_test.POJO.data.StoreOutAll;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface StoreOutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storeout_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long storeOutID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storeout_table
     *
     * @mbg.generated
     */
    int insert(StoreOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storeout_table
     *
     * @mbg.generated
     */
    int insertSelective(StoreOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storeout_table
     *
     * @mbg.generated
     */
    StoreOut selectByPrimaryKey(Long storeOutID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storeout_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StoreOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storeout_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StoreOut record);

    List<StoreOutAll> selectByWareIDIn(@Param("wareID") Long wareID, @Param("state") int state);

    List<StoreOutAll> selectByWareIDInTest(@Param("wareID") Long wareID, @Param("state") int state);//test

    List<StoreOutAll> selectByWareIDOut(@Param("wareID") Long wareID,@Param("state") int state);
}