package oil.oil_test.dao;

import oil.oil_test.POJO.User;
import oil.oil_test.POJO.data.UserAll;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long userID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbg.generated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Long userID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);

    UserAll userLogin(User user);

    List<UserAll> selectByGroupID(Long groupID); //传输基础参数时，mapper必须指定parameterType

    List<UserAll> selectByGroupName(@Param("zqName") String zqName, @Param("jtName")String jtName, @Param("ltName") String ltName);
}