package oil.oil_test.dao;

import oil.oil_test.POJO.UserPower;
import oil.oil_test.POJO.data.UserPowerAll;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface UserPowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpower_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long userPowerID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpower_table
     *
     * @mbg.generated
     */
    int insert(UserPower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpower_table
     *
     * @mbg.generated
     */
    int insertSelective(UserPower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpower_table
     *
     * @mbg.generated
     */
    UserPower selectByPrimaryKey(Long userPowerID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpower_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserPower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpower_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserPower record);

    List<UserPowerAll> selectPowerCode(Long record);

    int deleteByUserID(Long userID);
}